[package]
name = "pyth-tool"
description = "The priest for our oracle (it knows all the rituals)"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.0", features = ["derive", "cargo"]}
shell-words = "1.1.0"
